name:

on: push

jobs:
  markdown-to-pdf:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # We use `git describe` which requires tags
        with:
          fetch-depth: 0
      - name: "Install Dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install pandoc graphviz texlive-latex-extra texlive-latex-recommended texlive-font-utils
          mkdir -p usr/bin
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.6.4/pandoc-crossref-Linux-2.9.2.1.tar.xz -O - | tar -Jx -C usr/bin
          echo "$(pwd)/usr/bin" >> $GITHUB_PATH
      - name: "Markdown -> [pandox] -> [TeXLive] -> PDF"
        run: make
      - name: "Upload build directory"
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 1
      - name: "Create Release if Tagged"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            build/spec.pdf
            build/abi.pdf
