name: "Update Contributors"

on:
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout chipsalliance/firrtl-spec"
        uses: actions/checkout@v3
      - name: "Update Contributors In-Place"
        shell: bash
        run: |
          ./scripts/get-contributors.sh -g ${{ secrets.GITHUB_TOKEN }} > include/contributors.json
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          git diff >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: "Open PR If New Contributors"
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ci/update-contributors
          author: chiselbot <chiselbot@users.noreply.github.com>
          committer: chiselbot <chiselbot@users.noreply.github.com>
          reviewers: |
            seldridge
          title: Update Contributors
          body: |
            Add missing contributors.

            This is an automated PR generated by [this GitHub Action](https://github.com/chipsalliance/firrtl-spec/actions/workflows/update-contributors.yml).
          commit-message: |
            Add missing contributors.

            This is an automated commit.
